# my global config
global:
  scrape_interval:     20s
  evaluation_interval: 60s

scrape_configs:

- job_name: 'ipfs-node'
  metrics_path: '/debug/metrics/prometheus'
  static_configs:
  - targets: ['ipfs:5001']

